apiVersion: batch/v1
kind: CronJob
metadata:
  name: schedule-job
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: schedule
        spec:
          restartPolicy: Never
          containers:
            - name: python
              image: "{{ .Values.werf.image.schedule }}"
              workingDir: /app
              env:
                - name: REDIS_HOST
                  value: '{{ .Release.Name }}-redis-master'
                - name: BSCSCAN_API_KEY
                  value: "{{ .Values.bsc.apiKey }}"
